using CommunityToolkit.Maui;
using Microsoft.Extensions.DependencyInjection;
using SpiritSummoner.Presentation.Controls.SpiritControls;
using SpiritSummoner.Presentation.Controls.SquadControls;
using SpiritSummoner.Presentation.Models;
using SpiritSummoner.Presentation.Navigation;
using SpiritSummoner.Presentation.Services;
using SpiritSummoner.Presentation.Services.Caching;
using SpiritSummoner.Presentation.ViewModels.Battles;
using SpiritSummoner.Presentation.ViewModels.BottomSheet;
using SpiritSummoner.Presentation.ViewModels.BottomSheets;
using SpiritSummoner.Presentation.ViewModels.Chat;
using SpiritSummoner.Presentation.ViewModels.Collections;
using SpiritSummoner.Presentation.ViewModels.Guilds;
using SpiritSummoner.Presentation.ViewModels.Onboarding;
using SpiritSummoner.Presentation.ViewModels.Popups;
using SpiritSummoner.Presentation.ViewModels.Pouch;
using SpiritSummoner.Presentation.ViewModels.Quests;
using SpiritSummoner.Presentation.ViewModels.Shared;
using SpiritSummoner.Presentation.ViewModels.Shop;
using SpiritSummoner.Presentation.ViewModels.Spirits;
using SpiritSummoner.Presentation.ViewModels.Squads;
using SpiritSummoner.Presentation.ViewModels.StartUp;
using SpiritSummoner.Presentation.Views;
using SpiritSummoner.Presentation.Views.Battle;
using SpiritSummoner.Presentation.Views.BottomSheets;
using SpiritSummoner.Presentation.Views.BottomSheets.ChatSheets;
using SpiritSummoner.Presentation.Views.BottomSheets.Hub;
using SpiritSummoner.Presentation.Views.BottomSheets.Portal;
using SpiritSummoner.Presentation.Views.BottomSheets.SpiritSheets;
using SpiritSummoner.Presentation.Views.BottomSheets.SquadSheets;
using SpiritSummoner.Presentation.Views.Chats;
using SpiritSummoner.Presentation.Views.Collection;
using SpiritSummoner.Presentation.Views.Guilds;
using SpiritSummoner.Presentation.Views.Onboarding;
using SpiritSummoner.Presentation.Views.Popups;
using SpiritSummoner.Presentation.Views.Popups.BattlePopups;
using SpiritSummoner.Presentation.Views.Popups.CollectionPopups;
using SpiritSummoner.Presentation.Views.Popups.GuildPopups;
using SpiritSummoner.Presentation.Views.Popups.ItemPopups;
using SpiritSummoner.Presentation.Views.Popups.PlayerPopups;
using SpiritSummoner.Presentation.Views.Popups.QuestPopups;
using SpiritSummoner.Presentation.Views.Popups.Shared;
using SpiritSummoner.Presentation.Views.Pouch;
using SpiritSummoner.Presentation.Views.Quests;
using SpiritSummoner.Presentation.Views.Shop;
using SpiritSummoner.Presentation.Views.Shop.Controls;
using SpiritSummoner.Presentation.Views.Spirits;

namespace SpiritSummoner.Presentation.Configuration;

public static class DependencyInjection
{
	public static IServiceCollection AddPresentationServices(this IServiceCollection services)
	{
		ServiceCollectionServiceExtensions.AddSingleton<INavigationService, ShellNavigationService>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IBottomSheetService, BottomSheetService>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IPageCacheService, PageCacheService>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IPresentationCacheInitializationService, PresentationCacheInitializationService>(services);
		ServiceCollectionServiceExtensions.AddSingleton<PlayerInfoModel>(services);
		ServiceCollectionServiceExtensions.AddSingleton<NavBarViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<WelcomeViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<LoginViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<LoadingViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<QuestViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<QuestTaskViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<QuestParagraphViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<BattleViewModelRefactored>(services);
		ServiceCollectionServiceExtensions.AddTransient<BattleListViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<BattleRewardsViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<BattleTasksViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildPerksViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<ShopHubViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritCardViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritDetailsViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<EvolveViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<EvolveRequirementsViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritSquadViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<CollectionHubViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<PouchViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<BattleHubViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<MainViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<ChatViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<DirectMessageViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildChatThreadViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<NewGuildThreadSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildHubViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildShopViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildMembersViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildWarsViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildDefenderManagementViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildWarHistoryViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<ShopSpiritSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<HubSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<PortalSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<SavedSquadsSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<HeldItemSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<RegisterTermsSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<ConfirmUserNameSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<LinkAccountSheetViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildWarNotificationViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritsHoldNavigationSheetViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<ItemPopup, ItemPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<InsufficientFundsPopup, InsufficientFundsPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<FilterCollectionPopup, FilterCollectionPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<QuestRewardsPopup, QuestRewardsPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<SpiritOrbDropPopup, SpiritOrbDropPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<BattleSummaryPopup, BattleSummaryPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<BattleDebugLogPopup, BattleDebugLogPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<CreateGuildPopup, CreateGuildPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<GuildSearchFilterPopup, GuildSearchFilterPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<GuildInvitationsPopup, GuildInvitationsPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<InvitePlayerPopup, InvitePlayerPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<CustomAlertPopup, CustomAlertPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<CustomConfirmationPopup, CustomConfirmationPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<SearchPlayersPopup, SearchPlayersPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<SelectPlayerIconPopup, SelectPlayerIconPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<DailyGiftPopup, DailyGiftPopupViewModel>(services);
		ServiceCollectionExtensions.AddTransientPopup<GameNewsPopup, NewsDetailsPopupViewModel>(services);
		ServiceCollectionServiceExtensions.AddSingleton<SpiritCardModelCache>(services);
		ServiceCollectionServiceExtensions.AddSingleton<SpiritCardModelFactory>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritCardModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<MainPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<WelcomePage>(services);
		ServiceCollectionServiceExtensions.AddTransient<LoginPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<LoadingPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<QuestParagraphView>(services);
		ServiceCollectionServiceExtensions.AddTransient<BattleHubPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<ShopHubPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<MasterPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritVerticalCardView>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritSquadCardView>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritDetailsView>(services);
		ServiceCollectionServiceExtensions.AddTransient<EvolveView>(services);
		ServiceCollectionServiceExtensions.AddTransient<EvolveRequirementsPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<BattleView>(services);
		ServiceCollectionServiceExtensions.AddTransient<QuestView>(services);
		ServiceCollectionServiceExtensions.AddTransient<QuestTaskView>(services);
		ServiceCollectionServiceExtensions.AddTransient<BattleListView>(services);
		ServiceCollectionServiceExtensions.AddTransient<SavedSquadsBottomSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<HubBottomSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<PortalBottomSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritHoldNavigationSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildWarNotificationBottomSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<PouchView>(services);
		ServiceCollectionServiceExtensions.AddTransient<ShopSpiritBottomSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<HeldItemBottomSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildHubNewPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildMembersPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildWarsPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildWarBattleListPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildShopPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildDefenderManagementPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildWarHistoryPage>(services);
		ServiceCollectionServiceExtensions.AddTransient<ChatView>(services);
		ServiceCollectionServiceExtensions.AddTransient<DirectMessageView>(services);
		ServiceCollectionServiceExtensions.AddTransient<GuildChatThreadView>(services);
		ServiceCollectionServiceExtensions.AddTransient<NewGuildThreadBottomSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpiritVerticalCardCollectionView>(services);
		ServiceCollectionServiceExtensions.AddTransient<FullCollectionNew>(services);
		ServiceCollectionServiceExtensions.AddTransient<RegisterTermsSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<ConfirmUserNameSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<LinkAccountSheet>(services);
		ServiceCollectionServiceExtensions.AddTransient<OnboardingViewModel>(services);
		ServiceCollectionServiceExtensions.AddTransient<OnboardingDialoguePage>(services);
		ServiceCollectionServiceExtensions.AddTransient<OnboardingSpiritsRewardPage>(services);
		return services;
	}
}
