using Microsoft.Extensions.DependencyInjection;
using SpiritSummoner.Application.Auth;
using SpiritSummoner.Application.BatchUpdates;
using SpiritSummoner.Application.Interfaces;
using SpiritSummoner.Application.Services;
using SpiritSummoner.Application.Session;
using SpiritSummoner.Application.State;
using SpiritSummoner.Application.UseCases.Auth;
using SpiritSummoner.Application.UseCases.Battles;
using SpiritSummoner.Application.UseCases.Chat;
using SpiritSummoner.Application.UseCases.DailyGifts;
using SpiritSummoner.Application.UseCases.Guildmasterboard;
using SpiritSummoner.Application.UseCases.Guilds;
using SpiritSummoner.Application.UseCases.Items;
using SpiritSummoner.Application.UseCases.Players;
using SpiritSummoner.Application.UseCases.Quests;
using SpiritSummoner.Application.UseCases.Shop;
using SpiritSummoner.Application.UseCases.Spirits;

namespace SpiritSummoner.Application.Configuration;

public static class DependencyInjection
{
	public static IServiceCollection AddApplicationServices(this IServiceCollection services)
	{
		ServiceCollectionServiceExtensions.AddSingleton<BatchUpdateMerger>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IUpdatePriorityDeterminer, UpdatePriorityDeterminer>(services);
		ServiceCollectionServiceExtensions.AddSingleton<ISessionInitializationService, SessionInitializationService>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IPlayerStateService, PlayerStateService>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IGuildStateService, GuildStateService>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IAuthenticationOrchestrator, AuthenticationOrchestrator>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IRegistrationOrchestrator, RegistrationOrchestrator>(services);
		ServiceCollectionServiceExtensions.AddSingleton<ISessionInitializationOrchestrator, SessionInitializationOrchestrator>(services);
		ServiceCollectionServiceExtensions.AddTransient<LinkAccountUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GainExperienceUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<LevelUpPlayerUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SpendCurrencyUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<UpdateSquadUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<AddSpiritToSquadUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SearchPlayersUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SendFriendRequestUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<AcceptFriendRequestUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<DeclineFriendRequestUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetFriendsUseCase>(services);
		ServiceCollectionServiceExtensions.AddSingleton<RegeneratePlayerEnergyUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SwitchActiveSquadUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<AcquireSpiritUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<LevelUpSpiritUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<AssignStatPointsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ResetStatPointsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SellSpiritUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<EvolveSpiritUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ToggleSpiritFavoriteUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<EquipItemUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<UnequipItemUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<UnlockMoveUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SetActiveMoveUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SetSpiritNicknameUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<UnequipItemUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ValidateUnlockMoveUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ApplyMovesEditUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SetPartnerSpiritUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<UpdatePlayerIconUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<StartPVPBattleUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<StartQuestBattleUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<StartGuildWarBattleInitUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<StartFriendBattleUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<StartFriendBattleInitUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ExecuteBattleTurnUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<CompleteBattleUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<PreCommitBattleUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<RecordBattleStatisticsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetOnlinePlayersUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GenerateNPCOpponentsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SwitchSpiritUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetWarContributionSummaryUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ClaimDailyBattleChestUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetBattleTasksUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<UpdateBattleTaskProgressUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ClaimBattleTaskRewardUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetLeaderboardUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<CompleteQuestTaskUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetQuestAreasUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetQuestsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetQuestTasksForAreaUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ExecuteQuestBattleUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<PreCommitQuestBattleUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ResetRepeatableTaskUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<StartQuestUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<UpdateQuestProgressUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ExecuteQuestTaskUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ExecuteQuestTaskHoldUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<PurchaseShopItemUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<PurchaseSpiritUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetShopItemDetailsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetSpiritPreviewUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<PurchaseCraftingItemUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetShopItemsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<MarkShopItemsViewedUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetGuildDetailsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SearchGuildsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<JoinGuildUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<LeaveGuildUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<CreateGuildUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<UpdateGuildUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<CheckGuildNameAvailabilityUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ManageGuildMembersUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ManageGuildInvitationsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetPendingJoinRequestsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetPlayerInvitationsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<DisbandGuildUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<CancelDisbandGuildUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<AcceptInvitationUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<DeclineInvitationUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<RefreshDefenseUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<RegisterAsWarMemberUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<StartGuildWarBattleUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ManageDefendersUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetGuildPerksUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ActivateGuildPerkUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<RaidCrystalsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<ProcessWarBattleResultUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<RedeemDailyGiftUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetItemByIdUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetEquippableItemsUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetPlayerInventoryUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SendChatMessageUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetChatMessagesUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<CreateGuildThreadUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<GetGuildThreadMessagesUseCase>(services);
		ServiceCollectionServiceExtensions.AddTransient<SendGuildThreadMessageUseCase>(services);
		ServiceCollectionServiceExtensions.AddSingleton<IChatUnreadService, ChatUnreadService>(services);
		return services;
	}
}
